[package]
name = "libdcerpc-sys"
version = "0.1.0"
edition = "2021"
links = "dcerpc"

[build-dependencies]
cc.workspace = true
idl-compiler.workspace = true
system-deps.workspace = true
bindgen = "0.64.0"

[package.metadata.system-deps]
libbsd = "0.11"