[package]
name = "idl-compiler-sys"
version = "0.1.0"
edition = "2021"
links = "idl_compiler"

[build-dependencies]
cc.workspace = true
system-deps.workspace = true

[package.metadata.system-deps]
libbsd = "0.11"